# Generated by Django 5.0.4 on 2024-04-17 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('post', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('requirements', models.JSONField()),
                ('deadline', models.DateField()),
            ],
        ),
    ]
