# Generated by Django 5.0.4 on 2024-04-19 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='requirements',
        ),
        migrations.AddField(
            model_name='post',
            name='requirements',
            field=models.ManyToManyField(to='posts.requirement'),
        ),
    ]
