# Generated by Django 5.0.4 on 2024-04-24 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_alter_post_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='company',
        ),
    ]
