# Generated by Django 5.0.4 on 2024-04-24 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_remove_post_company_post_recruiter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='recruiter',
        ),
    ]
