# Generated by Django 5.0.4 on 2024-04-24 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_post_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='company',
            field=models.CharField(max_length=100),
        ),
    ]
