# Generated by Django 5.0.4 on 2024-04-18 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_remove_user_address_remove_user_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='address',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='city',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='company',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='country',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='cover_letter',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='cv',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='step',
        ),
    ]
