# Generated by Django 5.0.4 on 2024-04-18 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_remove_candidate_address_remove_candidate_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='company',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='cover_letter',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='cv',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='step',
            field=models.CharField(default='pending', max_length=100),
            preserve_default=False,
        ),
    ]
