# Generated by Django 5.0.4 on 2024-04-18 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_candidate_address_candidate_city_candidate_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='cover_letter',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='cv',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
