# Generated by Django 5.0.4 on 2024-04-18 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_recruiter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='step',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
