# Generated by Django 5.0.4 on 2024-04-26 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0013_application_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('f', 'female'), ('m', 'male')], default='m', max_length=1),
            preserve_default=False,
        ),
    ]
