# Generated by Django 5.0.4 on 2024-04-24 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_alter_candidate_step'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruiter',
            name='company',
            field=models.CharField(default='test', max_length=100),
            preserve_default=False,
        ),
    ]
