# Generated by Django 5.0.4 on 2024-04-30 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0002_remove_internship_interns_internship_interns'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internship',
            name='interns',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='internships', to='utils.intern'),
        ),
    ]
