# Generated by Django 5.0.4 on 2024-04-30 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0003_alter_internship_interns'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internship',
            name='interns',
        ),
        migrations.AddField(
            model_name='internship',
            name='interns',
            field=models.ManyToManyField(related_name='internships', to='utils.intern'),
        ),
    ]
