# Generated by Django 5.0.4 on 2024-05-02 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0005_alter_internship_interns'),
    ]

    operations = [
        migrations.AddField(
            model_name='intern',
            name='reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='intern',
            name='subject',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
