# Generated by Django 5.0.4 on 2024-05-03 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0006_intern_reference_intern_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='intern',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, default='2009-4-8'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='intern',
            name='id_internship',
            field=models.CharField(default=2009, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='intern',
            name='education',
            field=models.TextField(default=2009),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='intern',
            name='email',
            field=models.EmailField(default=2009, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='intern',
            name='name',
            field=models.CharField(default=2009, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='intern',
            name='phone',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='intern',
            name='reference',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='intern',
            name='skills',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='intern',
            name='subject',
            field=models.CharField(max_length=255),
        ),
    ]
